name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
      
    - name: Make API Request
      run: |
        curl -X POST https://msumgt-apiqa.egmu-research.org/api/Token \
        -H "accept: text/plain" \
        -H "Content-Type: application/json" \
        -d "{\"username\":\"test\",\"password\":\"test\"}"
